### ISSUE TITLE
Unauthenticated request to deep URL should redirect to login page

### ISSUE THREAD

**Issue by sbob909** [forcedotcom/IoraLite#2]
Accessing a deep IoraLite URL (e.g., https://ioralite.herokuapp.com/Iora_Targets?target=reports) while unauthenticated displays page without data. Should redirect to login page.

**Comment by sfdeveloperhub** [comment]
@sbob909 , please test. This should be addressed.

**Comment by sbob909** [comment]
Confirmed fix.
