### ISSUE TITLE
Datatables errors

### ISSUE THREAD

**Issue by sbob909** [forcedotcom/IoraLite#3]
"DataTables warning: table id=targets-table-report - Requested unknown parameter 'null' for row 0, column 2. For more information about this error, please see http://datatables.net/tn/4"

This error is appearing on pages with tables. Seems to appear after pulling in a report on demand (rather than using only reports in the originally collected set of reports). Perhaps the on-demand pull is missing some data that the table expects?

**Comment by sfdeveloperhub** [comment]
Update the rank to "Fetched on Demand" , to fill-in the empty column.

**Comment by sfdeveloperhub** [comment]
@sbob909 , please test. This should be addressed.

**Comment by sbob909** [comment]
Seems to be working without errors now for fetched reports.
