### ISSUE TITLE
Difficulties starting up with 'strict' mode and 'X-Content-Type: nosniff'

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/IoraLite#4]
I have deployed the app to Heroku.
Upon starting the app, the console log indicates : 

Did not parse stylesheet at 'https://xxx.herokuapp.com/bower_components/angular-loading-bar/build/loading-bar.css' because non CSS MIME types are not allowed in strict mode.
...
Did not load script at 'https://xxx.herokuapp.com/bower_components/jquery/dist/jquery.js' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
...

Can you help me get the right configuration to get IoraLite working ?

**Comment by sfdeveloperhub** [comment]
@AltiusRupert , thanks for reporting the issue and your interests in the tool. Can you please let me know the browser you are using ? Apparently looks like the file MIME type is not being set correctly for some reason. Will review.

@sbob909
